android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048M --add-opens jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED
systemProp.file.encoding=utf-8

# https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true
org.gradle.java.installations.paths=/nix/store/34vkf23nw2k7kh21bdczvphbixs4xxxy-zulu-ca-jdk-17.0.12,/nix/store/z6sy07psaxfanyd700hxsmig3zn0wxpx-zulu-ca-jdk-21.0.8
